blank_issues_enabled: false
contact_links:
- name: Community forums
  url: https://github.com/orgs/recaptime-dev/discussions
  about: This issue tracker is for holding log threads and usually locked from replies due to its nature. Please use the community forum if you have questions.